# DataSource Config
spring:
  mail:
    #编码格式
    default-encoding: UTF-8
    #采用QQ邮箱发送邮件
    host: smtp.126.com
    #发送人配置的用户名
    username: lunyang92851818@126.com
    #QQ邮箱中开通的服务密码，不是QQ密码
    password: WFKSHDZLNXHBZDFV

  redis:
    database: 0
    host: 47.101.194.177
    port: 6379
    jedis.pool.max-active: 2000
    jedis.pool.max-idle: 100
    jedis.pool.min-idle: 50
    timeout: 3000
  aop:
    proxy-target-class: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.194.177:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: t
    password: 1766468434
    initialSize: 5
    minIdle: 10
    maxActive: 1000
      #配置获取连接等待超时的时间
    maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
      #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    testWhileIdle: true
      #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
      #指明是否在归还到池中前进行检验
    testOnReturn: false

    hikari:
      max-lifetime: 120000

shiro-redis:
  enabled: true
  redis-manager:
    host: 47.101.194.177:6379