# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.194.177:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: t
    password: 1766468434
    hikari:
      max-lifetime: 120000
shiro-redis:
  enabled: true
  redis-manager:
    host: 47.101.194.177:6379